"""init

Revision ID: 42373d23f04e
Revises: 
Create Date: 2026-04-19 12:48:41.928248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42373d23f04e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_pro', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('resume_visited', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('interview_visited', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('aptitude_accuracy', sa.Float(), nullable=False, server_default=sa.text('0.0')),
    sa.Column('streak_days', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=False, server_default=sa.text('0.0')),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('interview_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=False),
    sa.Column('company_type', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('strengths', sa.String(length=2000), nullable=True),
    sa.Column('weaknesses', sa.String(length=2000), nullable=True),
    sa.Column('topics_to_revise', sa.String(length=2000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_user_email'), 'interview_sessions', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_user_email'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
