"""add activity fields

Revision ID: d1253bc20981
Revises: 42373d23f04e
Create Date: 2026-04-19 22:43:21.930917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1253bc20981'
down_revision: Union[str, None] = '42373d23f04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_visited', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('interview_visited', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('aptitude_accuracy', sa.Float(), nullable=False, server_default=sa.text('0.0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aptitude_accuracy')
    op.drop_column('users', 'interview_visited')
    op.drop_column('users', 'resume_visited')
    # ### end Alembic commands ###
